package views;

import dao.InventoryDAO;
import enums.UserRole;
import jakarta.persistence.EntityManager;
import jakarta.persistence.TypedQuery;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Inventory;
import models.User;
import utils.JPAUtil;
import views.inventory.InventoryManagementView;
import views.inventory.InventoryRegisterView;
import views.recipes.RecipeRegisterView;
import views.recipes.RecipeView;

/**
 *
 * @author joaopedro
 */
public class DashBoardView extends javax.swing.JFrame {

	/**
	 * Creates new form DashBoardView
	 */
	public DashBoardView(User user) {
		initComponents();
		setupUIForUser(user);
		loadInventoryData();
	}

	private void setupUIForUser(User user) {

		JOptionPane.showMessageDialog(null, "Welcome, " + user.getFullName() + "!" + "Your role is: " + user.getRole().toString());

		// Configurar visibilidade dos botões baseado no cargo
		boolean isManager = user.getRole().equals(UserRole.MANAGER);
		boolean isKitchen = user.getRole().equals(UserRole.KITCHEN);
		boolean isStorage = user.getRole().equals(UserRole.STORAGE);

		btn_AddRecipe.setVisible(user.getRole().equals(UserRole.MANAGER) || user.getRole() == (UserRole.KITCHEN));
		btn_Inventory.setVisible(user.getRole().equals(UserRole.MANAGER) || user.getRole().equals(UserRole.STORAGE));
		btn_Recipe.setVisible(user.getRole().equals(UserRole.MANAGER) || user.getRole().equals(UserRole.KITCHEN));
		btn_Report.setVisible(user.getRole().equals(UserRole.MANAGER) || user.getRole().equals(UserRole.STORAGE));
		btn_Search.setVisible(user.getRole().equals(UserRole.MANAGER) || user.getRole().equals(UserRole.STORAGE));
		btn_Supplier.setVisible(user.getRole().equals(UserRole.MANAGER) || user.getRole().equals(UserRole.STORAGE));
		btn_addIngred.setVisible(user.getRole().equals(UserRole.MANAGER) || user.getRole().equals(UserRole.STORAGE));
		btn_back.setVisible(true);

		loadInventoryData();
	}



	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_ExpIngred1 = new javax.swing.JPanel();
        jPanel_side = new javax.swing.JPanel();
        btn_addIngred = new javax.swing.JButton();
        btn_Inventory = new javax.swing.JButton();
        btn_AddRecipe = new javax.swing.JButton();
        btn_Recipe = new javax.swing.JButton();
        btn_Report = new javax.swing.JButton();
        btn_Supplier = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        jPanel_ExpIngred = new javax.swing.JPanel();
        txtF_Search = new javax.swing.JTextField();
        btn_Search = new javax.swing.JButton();
        jPanel_ExpIngred2 = new javax.swing.JPanel();
        jPanel_ExpIngred3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPanel_ExpIngred1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel_ExpIngred1Layout = new javax.swing.GroupLayout(jPanel_ExpIngred1);
        jPanel_ExpIngred1.setLayout(jPanel_ExpIngred1Layout);
        jPanel_ExpIngred1Layout.setHorizontalGroup(
            jPanel_ExpIngred1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 263, Short.MAX_VALUE)
        );
        jPanel_ExpIngred1Layout.setVerticalGroup(
            jPanel_ExpIngred1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_side.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_addIngred.setText("Add Ingredient");
        btn_addIngred.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_addIngred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addIngredActionPerformed(evt);
            }
        });

        btn_Inventory.setText("Inventory");
        btn_Inventory.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Inventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InventoryActionPerformed(evt);
            }
        });

        btn_AddRecipe.setText("Add Recipe");
        btn_AddRecipe.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_AddRecipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddRecipeActionPerformed(evt);
            }
        });

        btn_Recipe.setText("Recipes");
        btn_Recipe.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Recipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RecipeActionPerformed(evt);
            }
        });

        btn_Report.setText("Report");
        btn_Report.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ReportActionPerformed(evt);
            }
        });

        btn_Supplier.setText("Suppliers");
        btn_Supplier.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SupplierActionPerformed(evt);
            }
        });

        btn_back.setText("<-");
        btn_back.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        jPanel_ExpIngred.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel_ExpIngredLayout = new javax.swing.GroupLayout(jPanel_ExpIngred);
        jPanel_ExpIngred.setLayout(jPanel_ExpIngredLayout);
        jPanel_ExpIngredLayout.setHorizontalGroup(
            jPanel_ExpIngredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );
        jPanel_ExpIngredLayout.setVerticalGroup(
            jPanel_ExpIngredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        txtF_Search.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn_Search.setText("Search");
        btn_Search.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchActionPerformed(evt);
            }
        });

        jPanel_ExpIngred2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel_ExpIngred2Layout = new javax.swing.GroupLayout(jPanel_ExpIngred2);
        jPanel_ExpIngred2.setLayout(jPanel_ExpIngred2Layout);
        jPanel_ExpIngred2Layout.setHorizontalGroup(
            jPanel_ExpIngred2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 314, Short.MAX_VALUE)
        );
        jPanel_ExpIngred2Layout.setVerticalGroup(
            jPanel_ExpIngred2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );

        jPanel_ExpIngred3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel_ExpIngred3Layout = new javax.swing.GroupLayout(jPanel_ExpIngred3);
        jPanel_ExpIngred3.setLayout(jPanel_ExpIngred3Layout);
        jPanel_ExpIngred3Layout.setHorizontalGroup(
            jPanel_ExpIngred3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );
        jPanel_ExpIngred3Layout.setVerticalGroup(
            jPanel_ExpIngred3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel_sideLayout = new javax.swing.GroupLayout(jPanel_side);
        jPanel_side.setLayout(jPanel_sideLayout);
        jPanel_sideLayout.setHorizontalGroup(
            jPanel_sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_sideLayout.createSequentialGroup()
                .addGroup(jPanel_sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_sideLayout.createSequentialGroup()
                        .addGroup(jPanel_sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_sideLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel_sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_AddRecipe, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_Inventory, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_addIngred, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel_sideLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_sideLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel_sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_Supplier, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_Report, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_Recipe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel_sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_sideLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtF_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_sideLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jScrollPane2)))
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_sideLayout.createSequentialGroup()
                        .addContainerGap(217, Short.MAX_VALUE)
                        .addComponent(jPanel_ExpIngred, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jPanel_ExpIngred2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jPanel_ExpIngred3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
        );
        jPanel_sideLayout.setVerticalGroup(
            jPanel_sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_sideLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel_sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_ExpIngred3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_ExpIngred, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_ExpIngred2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_addIngred)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_AddRecipe)
                    .addGroup(jPanel_sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtF_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_Search)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_sideLayout.createSequentialGroup()
                        .addComponent(btn_Inventory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Recipe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Supplier)
                        .addGap(14, 14, 14)
                        .addComponent(btn_Report)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_side, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_side, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addIngredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addIngredActionPerformed
		// TODO add your handling code here:
		InventoryRegisterView rv = new InventoryRegisterView();
		rv.setVisible(true);
    }//GEN-LAST:event_btn_addIngredActionPerformed

    private void btn_AddRecipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddRecipeActionPerformed
		// TODO add your handling code here:
		RecipeRegisterView rr = new RecipeRegisterView();
		rr.setVisible(true);
    }//GEN-LAST:event_btn_AddRecipeActionPerformed

    private void btn_InventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InventoryActionPerformed
		// TODO add your handling code here:
		InventoryManagementView iv = new InventoryManagementView();
		iv.setVisible(true);
    }//GEN-LAST:event_btn_InventoryActionPerformed

    private void btn_RecipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RecipeActionPerformed
		// TODO add your handling code here:
		RecipeView rv = new RecipeView();
		rv.setVisible(true);
    }//GEN-LAST:event_btn_RecipeActionPerformed

    private void btn_SupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SupplierActionPerformed
		// TODO add your handling code here:
		SupplierView sv = new SupplierView();
		sv.setVisible(true);
    }//GEN-LAST:event_btn_SupplierActionPerformed

    private void btn_ReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ReportActionPerformed
		// TODO add your handling code here:

    }//GEN-LAST:event_btn_ReportActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
		// TODO add your handling code here:
		this.dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchActionPerformed
		// TODO add your handling code here:
		String searchTerm = txtF_Search.getText().trim();
		if (searchTerm.isEmpty()) {
			loadInventoryData(); // Recarrega todos se estiver vazio
			return;
		}

		try {
			InventoryDAO dao = new InventoryDAO();
			EntityManager em = JPAUtil.getEntityManager();
			TypedQuery<Inventory> query = em.createQuery(
					"SELECT i FROM Inventory i WHERE LOWER(i.name) LIKE LOWER(:term)", Inventory.class);
			query.setParameter("term", "%" + searchTerm + "%");
			List<Inventory> items = query.getResultList();

			DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
			model.setRowCount(0); // Limpa a tabela

			for (Inventory item : items) {
				model.addRow(new Object[]{
					item.getId(),
					item.getName(),
					item.getQuantity(),
					item.getMin_stock()
				});
			}
		} catch (Exception e) {
			JOptionPane.showMessageDialog(this, "Erro na busca: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
		}


    }//GEN-LAST:event_btn_SearchActionPerformed

	private void loadInventoryData() {
		try {
			InventoryDAO dao = new InventoryDAO();
			List<Inventory> items = dao.readALL();

			// Modelo de tabela
			DefaultTableModel model = new DefaultTableModel(
					new Object[]{"ID", "Nome", "Quantidade", "Unidade", "Estoque Mínimo"}, 0);

			for (Inventory item : items) {
				model.addRow(new Object[]{
					item.getId(),
					item.getName(),
					item.getQuantity(),
					item.getMin_stock()
				});
			}

			jTable1.setModel(model);

		} catch (Exception e) {
			JOptionPane.showMessageDialog(this,
					"Erro ao carregar dados: " + e.getMessage(),
					"Erro", JOptionPane.ERROR_MESSAGE);
		}
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AddRecipe;
    private javax.swing.JButton btn_Inventory;
    private javax.swing.JButton btn_Recipe;
    private javax.swing.JButton btn_Report;
    private javax.swing.JButton btn_Search;
    private javax.swing.JButton btn_Supplier;
    private javax.swing.JButton btn_addIngred;
    private javax.swing.JButton btn_back;
    private javax.swing.JPanel jPanel_ExpIngred;
    private javax.swing.JPanel jPanel_ExpIngred1;
    private javax.swing.JPanel jPanel_ExpIngred2;
    private javax.swing.JPanel jPanel_ExpIngred3;
    private javax.swing.JPanel jPanel_side;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtF_Search;
    // End of variables declaration//GEN-END:variables
}
