package views;

import dao.UserDAO;
import enums.UserRole;
import enums.UserSession;
import javax.swing.JOptionPane;
import models.User;

/**
 *
 * @author joaopedro
 */
public class LoginView extends javax.swing.JFrame {

	/**
	 * Creates new form LoginView
	 */
	public LoginView() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Login = new javax.swing.JPanel();
        pw_field = new javax.swing.JPasswordField();
        tf_User = new javax.swing.JTextField();
        btn_login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_Gerente = new javax.swing.JButton();
        btn_Estoque = new javax.swing.JButton();
        btn_Cozinha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel_Login.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel_Login.setToolTipText("");

        pw_field.setText("jPasswordField1");
        pw_field.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tf_User.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn_login.setText("Login");
        btn_login.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        jLabel1.setText("User:");

        jLabel2.setText("Password:");

        btn_Gerente.setText("Teste Gerente");
        btn_Gerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GerenteActionPerformed(evt);
            }
        });

        btn_Estoque.setText("Teste Estoque");
        btn_Estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EstoqueActionPerformed(evt);
            }
        });

        btn_Cozinha.setText("Teste Cozinha");
        btn_Cozinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CozinhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_LoginLayout = new javax.swing.GroupLayout(jPanel_Login);
        jPanel_Login.setLayout(jPanel_LoginLayout);
        jPanel_LoginLayout.setHorizontalGroup(
            jPanel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_LoginLayout.createSequentialGroup()
                .addGroup(jPanel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_LoginLayout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel2))
                    .addGroup(jPanel_LoginLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btn_Gerente)
                        .addGap(82, 82, 82)
                        .addComponent(btn_Estoque)
                        .addGap(80, 80, 80)
                        .addComponent(btn_Cozinha))
                    .addGroup(jPanel_LoginLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addGroup(jPanel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pw_field, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_User, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel_LoginLayout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel_LoginLayout.setVerticalGroup(
            jPanel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_LoginLayout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_User, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(3, 3, 3)
                .addComponent(pw_field, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addGroup(jPanel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Gerente)
                    .addComponent(btn_Estoque)
                    .addComponent(btn_Cozinha))
                .addGap(69, 69, 69))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Login, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed

		String username = tf_User.getText().trim();
		String password = new String(pw_field.getPassword());

		// Validação básica
		if (username.isEmpty() || password.isEmpty()) {
			JOptionPane.showMessageDialog(this,
					"Por favor, preencha todos os campos",
					"Erro de Login",
					JOptionPane.ERROR_MESSAGE);
			return;
		}

		try {
			UserDAO userDAO = new UserDAO();
			User user = userDAO.authenticate(username, password);

			if (user != null) {
				// Login bem-sucedido
				UserSession.getInstance().login(user);

				// Abre a dashboard
				DashBoardView dashboard = new DashBoardView(user);
				dashboard.setVisible(true);

				// Fecha a tela de login
				this.dispose();
			}
			else {
				JOptionPane.showMessageDialog(this,
						"Usuário ou senha inválidos",
						"Erro de Login",
						JOptionPane.ERROR_MESSAGE);
			}
		} catch (Exception e) {
			JOptionPane.showMessageDialog(this,
					"Erro durante o login: " + e.getMessage(),
					"Erro",
					JOptionPane.ERROR_MESSAGE);
		}
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_GerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GerenteActionPerformed
		// TODO add your handling code here:
		tf_User.setText("Adm");
		pw_field.setText("Adm123");
		btn_login.doClick();
    }//GEN-LAST:event_btn_GerenteActionPerformed

    private void btn_EstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EstoqueActionPerformed
		// TODO add your handling code here:
		tf_User.setText("Stg");
		pw_field.setText("admin123");
		btn_login.doClick();
    }//GEN-LAST:event_btn_EstoqueActionPerformed

    private void btn_CozinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CozinhaActionPerformed
		// TODO add your handling code here:
		tf_User.setText("Ktn");
		pw_field.setText("admin123");
		btn_login.doClick();
    }//GEN-LAST:event_btn_CozinhaActionPerformed

	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new LoginView().setVisible(true);
			}
		});

	}

	private void openDashboard() {

		User user = UserSession.getInstance().getCurrentUser();

		DashBoardView dashboard = new DashBoardView(user);
		dashboard.setVisible(true);

		// Fecha a tela de login
		LoginView lv = new LoginView();
		lv.dispose();
	}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cozinha;
    private javax.swing.JButton btn_Estoque;
    private javax.swing.JButton btn_Gerente;
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel_Login;
    private javax.swing.JPasswordField pw_field;
    private javax.swing.JTextField tf_User;
    // End of variables declaration//GEN-END:variables
}
